AWSTemplateFormatVersion: "2010-09-09"
Description: To launch three virtual machines I can deploy playbooks on
Resources:
  MyServer1:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: practice-servers
      ImageId: ami-0fc5d935ebf8bc3bc
      InstanceType: t2.medium
      Tags:
        - Key: Ansible Machine
          Value: Production
      UserData:
        Fn::Base64:
          #!/bin/bash
          sudo apt-get update
          sudo apt-get install -y ansible
  MyServer2:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: practice-servers
      ImageId: ami-0fc5d935ebf8bc3bc
      InstanceType: t2.medium
      Tags:
        - Key: Ansible Machine
          Value: Production
      UserData:
        Fn::Base64:
          #!/bin/bash
          sudo apt-get update
          sudo apt-get install -y ansible
  ServerSecurity: 
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: My security group to allow access on ports 80 and 22
      GroupName: MyAnsibleSG
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 192.168.146.131/24
      Tags: 
        - Key: SG
          Value: MyAnsibleSG
      VpcId: vpc-0a4ccbba02c46da2b
